spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Auth Service Route - Public endpoints
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authService
                fallbackUri: forward:/fallback/auth
            - StripPrefix=1

        # Data Service Route - Protected endpoints
        - id: data-service
          uri: lb://data-service
          predicates:
            - Path=/api/data/**
          filters:
            - name: JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: dataService
                fallbackUri: forward:/fallback/data
            - StripPrefix=1

        # Public endpoints (no auth required)
        - id: public-endpoints
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/register
            - Path=/api/auth/login
            - Path=/api/auth/guest
            - Path=/api/auth/refresh
          filters:
            - StripPrefix=1

        # Service Discovery Route
        - id: eureka-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

      default-filters:
        - AddRequestHeader=X-Gateway-Request, true
        - AddResponseHeader=X-Gateway-Response, true

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-value: ${JWT_SECRET:nUfJ0IIEZWvOFqlud2hLrdVgGkYLYNH6JR6NkF6bAMq+yhdoQrah87JcbUsnXzQ4}

server:
  port: 8086

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      authService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
      dataService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: INFO